### ISSUE TITLE
Android M (6.0)  compatability

### ISSUE THREAD

**Issue by edog1973** [openhab/openhab.android#142]
I have a device running Android M (6.0).  The openhab  app is non functional on this device.  I always get the 'Please check openHAB is running... ' message when I open it.  I've noticed that Settings -> Apps -> openHAB -> permissions only lists "Location".  My second device running Android 5.1 shows a long list of  permissions which are missing under Android M. The Android 5.1 device also functions as expected.   I've attached screen captures from both devices to show the difference.

![permissions on android 6](https://cloud.githubusercontent.com/assets/5891504/10947487/09c89182-82dd-11e5-8881-575d666107c4.png)

![permissions on android 5 1](https://cloud.githubusercontent.com/assets/5891504/10947492/0e237f12-82dd-11e5-99f3-53c725445f51.png)

**Comment by bartcerneels** [comment]
I can confirm habdroid version 1.7.0.1 running on a nexus 9 with android 6.0 is not functioning.
It seems to detect my openhab installation on the local network but does not display any sitemap.

When connecting over https the logs show this error:
2015-11-25 19:13:01.500 [WARN ] [org.eclipse.jetty.io.nio      ] - javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
2015-11-25 19:13:02.011 [WARN ] [org.eclipse.jetty.io.nio      ] - javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?

I suspect android might be terminating the connection because of a weak Diffie-Hellman key that is still used. Recent chrome versions don't connect to servers using this key anymore. So I suspect android clients to do the same now.

**Comment by bartcerneels** [comment]
While connecting locally using the automatic discovery didn't work (possibly an openhab server issue, not habdroid). So I used the regular HTTP url as remote address it works. Using unencrypted connection, with clear text authentication, is not something I want to do, but at least I can keep using habdroid on my own network like this.

**Comment by kaikreuzer** [comment]
I would guess this is rather a problem within the openHAB 1.7 runtime then - I can successfully use HABDroid on a Nexus 5,7,9 with openHAB 1.4 as well as openHAB 2.0.
If this is the case, you might want to enter a critical issue at https://github.com/openhab/openhab/issues instead.

**Comment by elisman** [comment]
Have you tried installing a snapshot of the App? I am running habdroid version 1.7.1 (an older snapshot version - but newer as the version in the Google App Store) with openHAB version 1.7.1. Everything works fine.

However, the persmission settings for the App look the same as above in the screenshot.

**Comment by digitaldan** [comment]
Is this still valid ?

**Comment by edog1973** [comment]
I do not believe so.  I've moved on to the newest 6.0.1 Android build and
am no longer seeing the issue.

**Comment by digitaldan** [comment]
Thanks
