### ISSUE TITLE
Unknown infos from server 2.0 beta 3

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab.android#191]
openHAB server 2.0 beta 3
HABdroid 1.8.3

When opening "infos openHAB" from the top right menu, I got "Unknown" for the 2 informations when my running server is 2.0 beta 3.

**Comment by digitaldan** [comment]
I don't think this was ever working and should probably be removed, openHAB servers do not have a REST endpoint to give server info, so I'm not sure how we would support this feature.

**Comment by lolodomo** [comment]
It is working with 1.x server.

**Comment by digitaldan** [comment]
Its looking for a static file called "version", which does not exist in OH2, and I seemed to not have it on my 1.x installs (not sure why?).  Also it was looking for the static  files  "UUID" and "secret" which for good reason are not exposed via http anymore in OH2.  If OH2 supports a version endpoint then I think it makes sense to support that one part, I would vote to remove the secret and uuid since I do not believe there is value in viewing those and OH2 won't expose those.

**Comment by kaikreuzer** [comment]
OH2 provides a version of its REST API on http://demo.openhab.org:9080/rest/:
```json
{
   "version":"0.8.0.201605191852",
   ...
}
```
A UUID is available at http://demo.openhab.org:9080/rest/uuid
Secret indeed isn't exposed anymore!

**Comment by kaikreuzer** [comment]
Note that this version is usable for determining how to use the REST API, but not for showing an OH version number in the app.

**Comment by digitaldan** [comment]
Well then for oh2 I can at least show the rest version and humid, I think removing the secret would then be appropriate !
