### ISSUE TITLE
Contributing - clarification

### ISSUE THREAD

**Issue by Br3nda** [openhab/openhab.android#207]
CONTRIBUTING.md states:

`
Discuss your design on the mailing list
We recommend discussing your plans in the issue tracker 
`

Can you clarify? Is there a mailing list somewhere? Can the mailing list be linked to here to make it easier to find? Or is there only the issue tracker? - should I be doing *both* a mailing list post and raising an issue?

**Comment by digitaldan** [comment]
My opinion is that for small changes and enhancements, submitting a PR is discussion enough. For larger changes I would use an issue to discuss first since devs who care will monitor issues here.  I like the forum https://community.openhab.org for discussing new features vs behind the scene changes, I think getting our user's perspective and interest on larger new features is important to keep the project focused on what our community really wants.
