### ISSUE TITLE
HABDroid opening wrong "sub-page" when navigating, title is correct

### ISSUE THREAD

**Issue by SierraNL** [openhab/openhab.android#246]
I use HABDroid with a LG Nexus 5x running Android 7 (also had the problem with 6).
It works fine, but every now and then (20% of the time) when I navigate through my sitemap, another sub-page opens instead of the one I selected. But the correct title is shown at the top. 

Navigating back and to the same sub-page again works.
##

**Comment by Br3nda** [comment]
Confirmed - i see this several times a day too.

**Comment by tsheldon** [comment]
+1  I see it as well

**Comment by hannibal85** [comment]
+1
Same here with Android 5.1

**Comment by muaythai2006** [comment]
same here

**Comment by mkotsbak** [comment]
I often see this too. Quite annoying. For me it only happens when I have navigated away from the app and is moving opening it again. Then the first page I select will have the correct name, but the content of the last visited page.

I never see it while navigating inside the app, so I assume this is some sort of error saving state when the app is inactive.

**Comment by hazzeh** [comment]
The root cause is that StateRetainFragment does not save the current fragment list when the app is sent to background (onSaveInstanceState). If the OS destroys the activity when it's in the background, the restoration will not be complete. Causing the faulty behaviour.
How to reproduce:

1. Configure the device to "At most 1 process" in "background process limit"-settings
2. Start habdroid and navigate to a subpage
3. Put the app in the background (switch to another app)
4. Switch back to habdroid and navigate to another subpage than previously

I'm not experienced in working with fragments, but some one else might be.

**Comment by FlorianSW** [comment]
From what I see in the code: The current state of the app is already saved and restored once the app goes to the background and is killed by the OS and restored after it get's started from the user again. However, the state is restored, but the main activity is shown, instead of the recently opened fragment, which results in the observed case, that the old fragment state is then loaded once the fragment is opened again.

I'm not sure, what the correct behaviour would be: Should the app restore the fragment, which was opened before the app resumes or should the app simply drop the fragment which was opened before, starts with the main activity and simply opens the correct fragment after the user selects a (new) one?

**Comment by mueller-ma** [comment]
At first I thought restoring is the best option, but when I think about it: Is it possible to say how long an app is usally in background until it is killed? It is unlikly that a user want to see the fragment he opend 2 hours before

**Comment by FlorianSW** [comment]
This should be different from device to device and use case to use case. It highly depends on how many memory is available and used by other apps, and so on. In fact: The system decides when and if an app is closed or not, it can be after 1 minute or after days. In my opinion, as we don't save things, which can't be easily opened again (like it would be for text inputs where text is already saved or something like this), we shouldn't try to restore the fragments. It would also be the easiest way I think.

If the users reports back, that they really want to restore the state, we can also re-implement that.
