### ISSUE TITLE
I did not recieve update 1.8.0.7

### ISSUE THREAD

**Issue by mueller-ma** [openhab/openhab.android#329]
My phone shows last update in March, on my computer July, but both show version 1.8.0.6 which should be 1.8.0.7 #323. I tested this on two devices.
I tried:

- Reboot the device
- Remove all data from play store app
- Deactivated Firewall on my smartphone
- Deactivated DNS Filter
- Reinstalled app

# Smartphone
![screenshot_20170714-210648](https://user-images.githubusercontent.com/22525368/28227049-a4ddb99e-68d8-11e7-845c-c6924d750bf5.png)
# PC
![play-store-pc](https://user-images.githubusercontent.com/22525368/28227061-ab8c0c50-68d8-11e7-8592-170e3ea6ab2b.JPG)

**Comment by digitaldan** [comment]
So google has overhauled the play store console, one of the features that is turned on by default is a very slow rollout of updated apps, the idea is you update 1% of your users per day instead of updating all users with a catastrophic  build.  I didn't realize this was the case so I just went in and pushed it to 100%, it was currently less the 10% installed at the moment.  

I'm hoping you get the update soon so we can close this!

**Comment by mueller-ma** [comment]
I've got it
