### ISSUE TITLE
Habdroid-authentication failed with mobile connection

### ISSUE THREAD

**Issue by Markus1985** [openhab/openhab.android#38]
Hi,
if I use Habdroid with WLAN-connection, everthing works fine. If I'm connected with 3G, I got an error message -authentication failed- or in german "Benutzeranmeldung fehlgeschlagen. Bitte prüfen Sie Benutzername/Passwort".
In my settings I leave openHAB URL empty (as I have read in previous discussions) and only put set openHAB remote URL with "https://my.openhab.org".

Thanks for your help!

**Comment by belovictor** [comment]
This probably means you didn't switch off local authentication in your openHAB, that's why remote connection through my.openhab.org doesn't pass through.

**Comment by mwick83** [comment]
Hi, I just started experimenting with openHAB, but I'm seeing a similar problem. I'm not using my.openhab.org, but a dynamic DNS provider directing to my dial-up Router, which in turn routes port 8443 to my openhab machine locally.
I turned security always on. And when I'm in my work's WiFi everything is fine, too. But not on 3G. When accessing openHAB directly through the browser it also works on 3G. But HABdroid tells me to check if my instance is accessible and the URL is correct.

Is there anything I can do to debug the problem?
Thanks for your help!

**Comment by belovictor** [comment]
a logcat for beginning would be great!

**Comment by mwick83** [comment]
Sorry for not answering. But I still didn't get time to investigate on the issue. I will get back to you when I get more time to work on my openHAB machine.

**Comment by belovictor** [comment]
I'm closing this as nobody seems to care about this problem.

**Comment by Seb-Maier** [comment]
I have the same problem with openHAB 2.1.0-1 (Release Build)
and openHAB Remote URL "https://myopenhab.org",
SSL Zertifikat and Hostname are ignored
openHAB App Version is 1.8.0.8

WLAN, also out of my home is working fine. Mobile access is not working and I get "Failed to connect to myopenhab.org/139.162.171.235:443"

**Comment by mueller-ma** [comment]
Just to be sure: you have set up myopenhab correctly?

And NEVER ignore ssl hostnames on the public internet!

**Comment by Seb-Maier** [comment]
Yes, I think so. myopenhab also works when I'm not at home and has WLAN access. Only mobile access doesn't work...

I have to ignore the SSL certifications. Otherwise I get the error message "SSL Handshake fehlgeschlagen - Sie brauchen vielleicht ein gültiges Client Zertifikat" (...you need a valid client certification)

I create a certification with...
`sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/openhab.key -out /etc/ssl/openhab.crt`
and 
`sudo openssl pkcs12 -export -out /etc/ssl/certificate.pfx -inkey /etc/ssl/openhab.key -in /etc/ssl/openhab.crt`

The pfx file I installed on my android phone but it doesn't work

**Comment by mueller-ma** [comment]
Do you have some kind of firewall?
