### ISSUE TITLE
Remove volume control for sliders and setpoints

### ISSUE THREAD

**Issue by boc-tothefuture** [openhab/openhab.android#446]
Per discussion in #442 volume controls should be removed for sliders and setpoints.  PR #442 already removes it for set point.  This issue is to gain consensus to remove it from sliders as well.

**Comment by boc-tothefuture** [comment]
@mueller-ma and @lolodomo  -
  I am not sure who has to weigh in on this one?  I have no problem doing the PR once we reach an agreement.

**Comment by mueller-ma** [comment]
I think we should remove that "feature". Volume buttons are for controlling volume and not for controlling the first entry in a list.

**Comment by boc-tothefuture** [comment]
Who needs to give the final approval?

**Comment by lolodomo** [comment]
Sorry I cannot comment as I don't understand what you want to change.
By the way, I am not the one who decide.

**Comment by maniac103** [comment]
@lolodomo The idea of this issue basically is reverting https://github.com/openhab/openhab.android/commit/058c3f9ad8238eacd3a021b63a023ab424ce6f0f

(:+1: for that, even though I have no say in anything here)

**Comment by mueller-ma** [comment]
Final approval should come from @digitaldan

**Comment by sansei4** [comment]
Why can't it be a point in the settings? I even didn't know that possibility before this discussion...

**Comment by boc-tothefuture** [comment]
@sansei4 -
  I think the issue is that no one really knows about it.. and the behavior isn't all that useful since it just controls the first slider on the screen..

As for why not make it a setting.  My thoughts are that it is more code to maintain, test, reason about for either minimal gain or in some viewpoints a negative user experience.

**Comment by FlorianSW** [comment]
More settings, even if it is useful for _some_ people, always means making the preferences of the app more and more complex. For a reaonable questionable feature, I wouldn't create a new setting, as is will lower usability of the preferences for most other people.

For the final approval thingi: I thought we're open source, so, if no-one (the community, including, but not limited to special people :)) has big objections on removing this feature, we should simply do it :) (and, if someone wants to re-introduce it later because there's a really good reason, we can always revert the PR)?

**Comment by mueller-ma** [comment]
@FlorianSW you're right!

**Comment by mueller-ma** [comment]
Fix in #447
