### ISSUE TITLE
Re-introduce "NFC to sitemap page"

### ISSUE THREAD

**Issue by FlorianSW** [openhab/openhab.android#527]
As mentioned by @kaikreuzer in https://github.com/openhab/openhab.android/issues/515#issuecomment-352048219 he's using the NFC functionality to "link to the current sitemap page" and advertises it whenever he can. As the main functionality of the NFC tag writing is still existing (for actions like toggle, on or off), re-introducing it would be pretty simple and not much code we would need to maintain.

This issue is for re-introducing this functionality.

**Comment by maniac103** [comment]
It's probably OK for now, but middle and long term I'd vote for making this feature more consistent by either
- moving it to a long-press action of the respective navigation drawer item or
- introducing a new activity that's accessed from the navigation drawer and allows assigning NFC tags to both sitemaps and switch items, fully replacing the long-press actions.

I'd favor the latter, because it allows getting rid of the totally undiscoverable long-press actions, but it's obviously more work.

**Comment by FlorianSW** [comment]
Would you like to open a new issue for that? Having a separate activity (like a wizard, where you first select what to link (item, sitemap), in the next step select what item/sitemap, and in the last step what action should happen?) sounds like a huge amount of work (however, I really like it!), which is also out of scope of this issue? :)

**Comment by kaikreuzer** [comment]
Yes, as mentioned in https://github.com/openhab/openhab.android/issues/515#issuecomment-352085047, I do not care too much, where it is as long as the feature is there. Thank you all!

**Comment by maniac103** [comment]
@FlorianSW I'd make that activity just display a list with all sitemaps and all assignable items, with appropriate section headers.

**Comment by mueller-ma** [comment]
The Signal uses long pressing on the header.
In [older versions](https://signal.org/assets/header/nietzche-04f33953b2398c045dc664aaa5bea560bf83ea6bf45b32a3066a766b5c10082d.png) you could press on the picture and open the contact app. They moved the picutere next to the name in the header. Now when you long press the header, the contact app opens and when you press the picture, you see it in fullscreen.

I think this solution is more discoverable.
