### ISSUE TITLE
Subscript text

### ISSUE THREAD

**Issue by 8666** [openhab/openhab.android#76]
Subscript HTML text is displayed fine in desktop/mobile browsers but not in HABDroid.

This should be rendered as ozone O&#8323; <code>O & # 8 3 2 3 ;<code> (without spaces)

**Comment by belovictor** [comment]
The current openHAB REST API doesn't have any requirments for formatting of label strings. So instead of requesting such a feature from the Android app it is better to request it from openHAB itself. If such a requirement will be included into REST API docs it will be implemented to all mobile apps then.
